json.id bracket.id
json.name bracket.name
json.user_id bracket.user_id
json.total_points bracket.total_points
json.round1 bracket.round1
json.round2 bracket.round2
json.round3 bracket.round3
json.round4 bracket.round4
json.round5 bracket.round5
json.round6 bracket.round6
json.round0 bracket.round0
json.created_at bracket.created_at
json.updated_at bracket.updated_at