json.id game.id
json.home_team_id game.home_team&.name
json.away_team_id game.away_team&.name
json.winner_team_id game.winner_team_id
json.winner_team_name game.winner_team&.name
json.round game.round
json.matrix game.matrix
json.created_at game.created_at
json.updated_at game.updated_at